import React from "react";
import Mbr from "../atoms/mbr/Mbr";
import {LANG} from "../hooks/hook";

export const en = {
  additionaly_setting_to_will_good_for_manage_ment: (
    <span>
      추가로 다음과 같은 설정을 해두시면 <Mbr /> 숙소운영에 도움이 될거에요! a
    </span>
  ),
  default_setting_is_compelted: (
    <span>
      기본설정이
      <Mbr /> 완료 되었습니다. a
    </span>
  ),
  make_it_easy_to_guide_accommodation_for_guests: (
    <span>
      게스트에게 숙소 이용 <Mbr />
      안내를 편리하게 해보세요. a
    </span>
  ),
  try_setting_it_up_different_prices_by_date: (
    <span>
      날자별로 가격을 다르게
      <Mbr /> 설정해보세요. a
    </span>
  ),
  Pricing: "가겨설정a",
  choseCheckInDate: "체크인 날자를 선택해 주세요.a",
  choseCheckOutDate: "체크아웃 날자를 선택해 주세요.a",
  checkIn: "체크인a",
  search: "검색a",
  price_setting_delete: "가격설정 삭제a",
  price_setting_delete_fail: "가격설정 삭제 실패a",
  search_reservation: "예약 검색하기a",
  reservation_date: "예약일자a",
  no_room_selected: "선택된방이 없습니다.a",
  go_to_set: "설정하러 가기a",
  accommodation_info: "숙박정보a",
  automatically_send_prompts_to_your_guests: (
    <span>
      게스트에게 안내문자를
      <Mbr />
      자동 발송해 보세요. a
    </span>
  ),
  sms_setting: "SMS설정a",
  checkOut: "체크아웃a",
  checkin_date: "체크인 날자a",
  checkout_date: "체크아웃 날자a",
  HM: "하우스 메뉴얼a",
  customer_inquiry: "고객문의a",
  bookingList: "예약목록a",
  expiry_date: "만료일a",
  cancleBooking: "예약취소a",
  sendSMS: "문자전송a",
  preferences: "환경설정a",
  delete: "삭제a",
  config: "설정a",
  preview: "미리보기a",
  eamil: "이메일a",
  agree_to_privacy_policy: "개인정보 이용동의a",
  connected_number: "연결번호a",
  connected_email: "연결이메일a",
  turn_off_alarm: "알림해제a",
  timeout_please_request_again: "시간초과 다시 요청 해주세요.a",
  there_is_an_alarm_set_note: "알람 설정된 메모가 있습니다.a",
  group_notification: "단체알림a",
  group_msg: "단체 메시지a",
  alarm: "알림a",
  alarm_transmission_failed: "알람 전송 실패a",
  alarm_transmission_completed: "알람 전송 성공a",
  page_does_not_exist: "페이지가 존재하지 않습니다.a",
  go_back_to_home: "홈으로 돌아가기a",
  noti_setting: "알람 설정a",
  note_updated: "메모 업데이트 완료a",
  note_updated_failed: "메모 업데이트 실패a",
  deleted_note_completed: "메모 삭제 완료a",
  deleted_note_failed: "메모 삭제 실패a",
  keep_noti: "계속 메모를 뛰우세요.a",
  close_today: "하루동안 뛰우지 마세요.a",
  today: "오늘a",
  block: "자리막음a",
  phone_authenticate: "휴대폰 인증하기a",
  authenticate: "인증하기a",
  certification_number: "인증번호a",
  today_sales: "오늘매출a",
  day_sales: "일매출a",
  this_month_sales: "이번달매출a",
  create_room: "방생성a",
  month_sales: "월매출a",
  year_sales: "년매출a",
  setting_fail: "설정실패a",
  division: "구분a",

  default_Setting_complted: "기본 설정완료a",
  exit_room_settings: "방설정 끝내기a",
  mobile_phone_verification_number: "휴대폰 인증번호a",
  mobile_phone_verification_completed: "휴대폰 인증완료a",
  mobile_phone_verification_failed: "휴대폰 인증실패a",
  certification_number_sent: "인증번호 발송완료a",
  certification_number_sent_fail: "인증번호 발송실패a",
  deleteBooking: "예약삭제a",
  minute: "분a",
  second: "초a",
  home: "홈a",
  block_place: "자리막기a",
  nextResv: "다음 예약 a",
  make_reservation: "예약하기a",
  sales: "매출a",
  support: "지원함a",
  unSupport: "지원안함a",
  room_select: "방 선택a",
  select_date: "날자선택a",
  check_selection: "선택 확인a",
  go_back: "돌아가기a",
  close: "닫기a",
  please_select_checkOut_date: "체크아웃 날자를 선택해주세요.a",
  there_is_no_room_in_selected_date: "해당날자에 예약가능한 방이 없습니다a",
  checkin_status: "체크인 현황a",
  send_notification: "알림 보내기a",
  change_date: "날자변경a",
  select_support_language: "지원 언어 선택a",
  allocation_calendar: "배정달력a",
  must_input_text_of_every_lang_you_supporting:
    "지원하는 모든 언어에 직접 기입 하셔야 합니다.a",
  memo_save_completed: "메모 저장완료a",
  memo_save_failed: "메모 저장실패a",
  menu_enable_set: "메뉴 사용 설정a",
  please_slect_date_at_calender: "달력에서 날자를 선택해주세요.a",
  HM_provides_guests_with_a_comfortable_and_convenient_accommodation_send_the_guide_page: (
    <span>
      하우스 메뉴얼은 게스트가 쉽고 편하게 숙소를 이용할 수 있도록 안내 페이지를
      송신합니다. <br />
      하우스 메뉴얼이 게스트의 숙소 이용법을 설명하는 수고를 덜어 줄겁니다. a
    </span>
  ),
  HM_set: "하우스 메뉴얼 설정a",
  menu_set: "메뉴설정a",
  lang_set: "언어설정a",
  using: "사용중a",
  not_use: "사용안함a",
  name_is_not_valid: "올바른 이름이 아닙니다.a",
  phoneNum_is_not_valid: "올바른 이름이 아닙니다.a",
  please_input_HM_title: "하우스메뉴얼 타이틀을 입력해주세요a",
  the_phone_number_set_is_not_valid: "설정된 전화번호가 유효하지 않습니다.a",
  the_email_set_is_not_valid: "설정된 이메일이 유효하지 않습니다.a",
  noti_target: "알림 대상a",
  noti_msg: "알림내용a",
  noti_level: "알람 중요도a",
  checkDelete: "개를 삭제하시겠습니까?a",
  check_net_status: "네트워크 연결상태를 확인해주세요!a",
  checkCheckInDate: "체크인 날자를 선택해 주세요.a",
  please_select_date: "날자를 선택해 주세요a",
  reservation_creation_complete: "예약 생성 완료a",
  reservation_creation_fail: "예약 생성 실패a",
  reservation_update: "예약 업데이트a",
  your_request_cannot_be_fulfilled_right_now:
    "지금은 요청사항을 수행수 없습니다.a",
  url_is_copied: "URL이 복사되었습니다.a",
  we_recommend_using_the_Chrome_browser_before_using_the_app:
    "앱사용 이전에 크롬 브라우저 사용을 권장합니다.a",
  room_create_completed: "방 생성완료a",
  room_create_fail: "방 생성실패a",
  this_is_an_old_browser_Problems_may_occur_while_using_the_service_Please_update_your_browser: (
    <span>
      오래된 브라우저 입니다. 서비스 이용중 문제가 발생할수 있습니다. <br />{" "}
      브라우저를 업데이트 해주세요. a
    </span>
  ),
  capacity_must_be_at_least_1_person: "수용인원은 1명 이상이여야 합니다.a",
  enter_room_type_name: "방타입명을 입력해주세요.a",
  update_to_recommended_browser_chrome: "권장 브라우저(Chrome)로 업데이트a",
  room_type_name: "방타입 이름a",
  room_delete_completed: "방 삭제완료a",
  room_update: "방 업데이트a",
  capacity: "수용인원a",
  select_roomType: "방타입 선택a",
  select_roomGender: "방성별 선택a",
  roomPic: "방사진a",
  room_type_basic_price: "방타입 기본가격a",
  room_type_desc: "방타입 추가설명a",
  room_update_fail: "방 업데잍 실패a",
  room_delete_fail: "방 삭제실패a",
  room_name_must_be_10_characters_or_less: "방이름은 10자 이하여야합니다.a",
  reservation_update_fail: "예약 업데이트 실패a",
  reservation_delete_complete: "예약 삭제 완료a",
  reservation_delete_fail: "예약 삭제 실패a",
  people_unit: "명a",
  house_info: "숙소정보a",
  house_delete_completed: "숙소삭제 완료a",
  house_delete_failed: "숙소삭제 실패a",
  failt_to_change_house: "숙소변경 실패a",
  changed_current_house: "현재숙소 변경a",
  none: "없음a",
  year: "년a",
  month: "월a",
  please_cancel_the_product_first: "상품을 먼저 해지 해주세요.a",
  calender_date: "달력날자a",
  date: "일a",
  till: "까지a",
  mon: "월a",
  tue: "월a",
  wed: "월a",
  thu: "목a",
  fri: "금a",
  sat: "토a",
  sun: "일a",
  next: "다음a",
  prev: "이전a",
  page: "페이지a",
  row: "열a",
  select: "선택a",
  fullRoom: "만실a",
  cancel: "취소a",
  confirm: "확인a",
  agree: "동의a",
  singUp_submit: "가입완료a",
  not_agree: "동의안함a",
  we_collect_your_personal_information_to_provide_the_service:
    "서비스 제공을 위해 귀하의 개인정보를 수집합니다.a",
  is_selected_info_collect: "선택 정보가 맞나요?a",
  selection_information_is_correct: "선택 정보가 맞습니다.a",
  privacy_item: "개인정보 항목a",
  consent_to_collection_of_personal_information: "개인정보 수집 동의a",
  purpose_of_collection: "수집 목적a",
  please_agree_collect_personal_info: "개인정보 수집에 동의해주세요a",
  the_minimum_personal_information_required_to_provide_the_service_is_required_to_use_the_service:
    "서비스 제공을 위해 필요한 최소한의 개인정보이므로 동의를 해주셔야 서비스를 이용하실수 있습니다a",
  smooth_reservation_management: "원활한 예약 관리a",
  six_months_after_stay: "숙박후 6개월a",
  if_you_violate_the_accommodation_policy_your_personal_information_will_be_saved_with_the_violation:
    "숙박 규정을 위반할 시 위반내용과 함께 개인정보가 저장됩니다.a",
  try_to_create_in_SMS_settings: "SMS 설정에서 생성 해보세요.a",
  write_a_description_of_the_menu: "해당 메뉴의 설명을 적어보세요.a",
  if_tou_enable_auto_send_msg_msg_will_send_autoMetically:
    "자동 발신을 해두시면해당 메세지는 설정된 상황에 맞게 자동으로 발송됨니다.a",
  retention_period: "보유 기간a",
  msg_content: "문자내용a",
  name: "이름a",
  view_terms: "약관보기a",
  contact: "연락처a",
  Headcount: "안원수a",
  find_destination: "대상찾기a",
  outgoing_destination: "발신대상a",
  auto_send_enable: "자동발신 활성화a",
  is_auto_send_enable: "자동발신 활성화 여부a",
  guest: "게스트a",
  login: "로그인a",
  signUp: "회원가입a",

  check_password: "비밀번호 확인a",
  password_condition: "* 특수문자 1개이상, 7~15자리 영문 숫자 조합a",
  room_info: "객실정보a",
  roomType: "방타입a",
  bedIndex: "침대번호a",
  season_basic_price: "시즌 기본 가격a",
  gender: "성별a",
  room: "방a",
  price: "가격a",
  upgrade: "업그레이드a",
  price_setting: "가격설정a",
  price_setting_complited: "가격설정 완료a",
  price_setting_failed: "가격설정 실패a",
  room_config: "방 설정a",
  available: "사용가능a",
  use: "사용하기a",
  save: "저장하기a",
  reservation_setting: "예약 설정a",
  unapplied: "적용안됨a",
  create_booking: "예약생성a",
  room_count: "방갯수a",
  add_room: "방추가a",
  system_config: "시스템 설정a",
  priority_changed: "순위 변경a",
  signup_complted: "회원가입 완료a",
  priority_change_fail: "순위 변경 실패a",
  display_deadline: "표시가한a",
  applied_product_type: "적용 상품타입a",
  Use_room_specific_tabs: "방타입별 탭을 사용합니다.a",
  basic_room_price: "기본 방 가격a",
  create_new_memo: "새로운 메모 쓰기a",
  auto_send_whether: "자동발신 여부a",
  system_related_settings: "시스템 관련 설정a",
  auto_send_target: "자동발신 대상a",
  send_target: "발신대상a",
  auto_send: "자동발신a",
  template_title: "템플릿 타이틀a",
  set_product_type: "상품 형태 설정a",
  auto_send_condition: "자동발신 상황a",
  we_will_contect_you_in_3_days: "3일 내로 담당자가 연락드릴 예정입니다.a",
  thank_you: "감사합니다.a",
  service_request_is_completed: "서비스 신청이 완료되었습니다a",
  appliedby_default_in_periods_with_no_price_set:
    "가격이 설정되어 있지 않은 기간 에서 기본으로 적용됨a",
  complete_the_reservation_creation: "예약생성을 완료합니다.a",
  sms_template: "문자템플릿a",
  send_sms: "문자발신a",
  new_booking: "새로운예약a",
  send_sms_complited: "발송완료a",
  send_sms_failed: "발송실패a",
  un_send_Sms: "발신안함a",
  male: "남a",
  female: "여a",
  make_payment: "결제하기a",
  payment_info: "결제정보a",
  password: "비밀번호a",
  send_status: "발신상태a",
  send_complete: "송신완료a",
  graph_shape: "그래프 형태a",
  send_fail: "송신실패a",
  payment_status: "결제상태a",
  total_price: "총가격a",
  normal_price: "정상가a",
  method_of_payment: "결제수단a",
  people: "명a",
  proceeding: "진행중a",
  memo: "메모a",
  HM_title: "하우스 메뉴얼 타이틀a",
  current_set_number: "현재 설정된 번호a",
  send_text_to_host: "호스트에게 문자 보내기a",
  check_location_with_google_map: "구글맵으로 위치 확인하기a",
  please_select_the_number_of_people: "인원수를 선택해주세요.a",
  payment_canceled: "결제가 취소 되었습니다.a",
  no_choosen_option: "선택사항이 없습니다.a",
  information_does_not_exist: "정보가 존재하지 않습니다...a",
  money_unit: "원a",
  send: "전송a",
  index: "번호a",
  waiting: "대기a",
  noti_title: "알림 제목a",
  noti_period: "알람 기간a",
  date_of_creation: "생성일시a",
  houseName: "숙소명a",
  house_type: "숙소타입a",
  house_reservation: "숙소 예약a",
  transmission_time: "전송시간a",
  time: "시간a",
  select_house_type: "숙소타입 선택a",
  polling_period: "풀링주기a",
  polling_period_setting: "풀링주기 설정a",
  default_system_setting: "기본 시스템 설정a",
  applicant: "신청자a",
  reservations_booked_directly_by_the_administrator_are_not_displayed:
    "관리자가 직접 예약한 예약은 표시되지 않습니다.a",
  homepage_application_date: "홈페이지 신청일시a",
  homepage_complete_estimated_date: "홈페이지 신청일시a",
  homepage_develope_status: "홈페이지 작업 현황a",
  is_apply_homepage: "홈페이지 신청여부a",
  displays_a_new_reservation_within_the_set_time:
    "설정된 시간 내의 새로운 예약을 표시합니다.a",
  are_you_sure_you_want_to_delete_this_guest:
    "해당 게스트를 삭제하시겠습니까?a",
  others_booked_by_the_reservation_will_not_be_erased:
    "해당 예약자가 예약한 다른 인원들은 지워지지 않습니다.a",
  reservation_is_completed: "예약이 완료되었습니다a",
  you_can_clear_the_display_by_clicking:
    " 클릭하여 해당 표시를 지울 수 있습니다a",
  assig_guest_specific_setting: "배정 게스트에 대한 상세설정기능a",
  server_will_check_if_there_is_a_new_reservation_once_every_set_number_by_ms:
    "설정한 숫자/ms 마다 한번씩 새로운 예약이 있는지 서버로부터 확인받습니다.a",
  if_there_is_a_new_reservation_the_new_reservation_will_be_displayed_without_refreshing_the_screen:
    "새로운 예약이 있다면 새로운 예약을 화면에 새로고침 없이 나타냅니다.a",
  if_you_have_problems_with_computer_performance_and_frequent_screen_updates_try_setting_a_higher_pooling_frequency:
    "컴퓨터 성능 및 잦은 화면 업데이트에 문제가 있을경우 풀링주기를 높게 설정해보세요.a",
  receiver: "수신자a",
  reservation_mark: "예약표시a",
  invalid_password: "잘못된 패스워드입니다.a",
  only_remove_that_guest: "해당 게스트만 제거a",
  remove_all_reservations_booked_together: "함께 예약된 모든 예약 인원 제거a",
  username_must_be_email: "아이디는 이메일 이여야합니다.a",
  copy_reservation_page_URL: "예약페이지 URL 복사a",
  login_complete: "로그인 완료a",
  auth: "인증a",
  house_create: (
    <span>
      숙소
      <Mbr />
      생성 a
    </span>
  ),
  product_registration: (
    <span>
      상품
      <Mbr />
      등록 a
    </span>
  ),
  this_price_modification_will_be_the_highest_priority_of_all_pricing:
    "해당 가격 수정은 모든 가격설정 중 최우선 적용 됩니다.a",
  daily_refine_price: "상세가격 수정a",
  house_setting_completed: "숙소설정 완료a",
  house_setting_failed: "숙소 설정 실패a",
  select_the_desired_setting_item: "원하는 설정 항목을 선택하세요.a",
  passwords_do_not_match: "패스워드가 일치하지 않습니다.a",
  cant_find_this_email: "해당 이메일을 찾을수 없습니다.a",
  if_you_set_up_an_SMS_template_you_can_conveniently_send_the_template_when_you_send_a_message:
    "SMS 템플릿을 설정해두시면 메세지를 보낼떄 해당 템플릿을 편리하게 보낼수 있습니다.a",
  view_SMS_history: "SMS 내역보기a",
  create_template: "템플릿 생성a",
  create_template_complited: "템플릿 생성완료a",
  create_template_failed: "템플릿 생성실패a",
  create_a_new_template: "새로운 템플릿을 생성하세요.a",
  send_type: "발신타입a",
  choose_product: "상품선택a",
  useing: "사용중a",
  msg: "메세지a",
  template_msg: "템플릿 메세지a",
  basic_offer: "기본제공a",
  light_type_layout: "light 타입 레이아웃a",
  heavy_type_layout: "heavy 타입 레이아웃a",
  inquire_separately: "별도문의a",
  please_inquire_separately: "별도 문의 바랍니다.a",
  additional_cost: "추가비용a",
  do_question: "문의하기a",
  none_product: "상품없음a",
  only_on_first_purchase: "첫구매시에만 발생a",
  take_a_look: "살펴보기a",
  apply: "신청하기a",
  dont_send: "발송안함a",

  goto_create_roomType: "방타입 생성하러가기a",
  product_application_completed: "상품 신청 완료a",
  product_application_failed: "상품 신청 실패a",
  reservation_confirm: "예약확인a",
  witch_statistics_do_you_want: "어떤 통계를 원하시나요?a",
  input_your_name_please: "이름을 입력해주세요.a",
  input_your_password_please: "비밀번호를 입력해주세요.a",
  please_enter_your_phone_number: "전화번호를 입력해주세요.a",
  date_of_statistics: "통계날자a",
  change_statistics: "통계변경a",
  which_unit_would_you_like_to_see: "어떤 단위로 보여 드릴까요?a",
  status: "상태a",
  Rooms: "객실a",
  day_of_week: "요일a",
  change: "변경a",
  checkin_change_fail: "체크인 변경 실패a",
  goto_reservation_list: "예약목록 보기a",
  non_members: "비회원a",
  statistics: "통계a",
  sales_statistics: "매출통계a",
  statistical_transformation: "통계 변환a",
  reservation_information: "예약정보a",
  reservation_lookup: "예약조회a",
  personnel: "인원a",
  reservation_did_date: "예약일시a",
  usage_amount: "이용금액a",
  reservation_memo: "예약메모a",
  block_highlights: "블록 하일라이트a",
  Apply: "적용a",
  date_of_stay: "숙박일자a",
  memo_content: "메모내용a",
  unappliy: "적용해제a",
  request_url: "요청URLa",
  item: "항목a",
  applied_url: "적용URLa",
  test_on_two_weeks: "이주일간 테스트 가능a",
  apply_layout: "신청레이아웃a",
  layout_cost: "레이아웃 비용a",
  applicant_contact: "신청자 연락처a",
  is_layout_paied: "레이아웃 비용 지불여부a",
  apply_color: "적용색상a",
  completed: "완료a",
  product_price: "상품금액a",
  modify: "수정a",
  free_experience: "무료체험a",
  // 상품에 관한 설명들
  product1_short1: "이주일간 테스트가능a",
  product1_short2: "사용해보고 결정하세요a",
  product1_short3: "지금 바로 시작할 수 있습니다.a",
  product2_short1: "중소숙박 최적화 서비스a",
  product2_short2: "필요한 서비스만 쉽고a",
  product2_short3: "간단하게 사용하세요.a",
  product3_short1: "호텔 대규모 솔루션 최적화a",
  product3_short2: "호텔관리자가 관여하여a",
  product3_short3: "다양한 서비스를 제공합니다.a",
  product4_short1: "숙박외 서비스 예약 및a",
  product4_short2: "다른 예약관리가 필요하신가요?a",
  product4_short3: "이상품을 선택하세요.a",
  product1_detail1: "상품을 구매하기전에 체험하기를 통해서 미리 체험해보세요.a",
  product1_detail2: "본상품은 구매전 체험을 위한 용도로 사용됩니다.a",
  product1_detail3:
    "잔다에서 무료로 제공하는 홈페이지를 제공받으실수 없습니다.a",
  product1_detail4:
    "대부분의 서비스를 사용가능하며 이주일후에는 사용이 불가능 합니다.a",
  product1_detail5:
    "기한이 끝난후에 새로운 상품을 적용하시면 계속 사용이 가능합니다.a",
  product2_detail1: "게스트 하우스 및 중소숙박에 최적화된 상품입니다.a",
  F_product2_detail2: (n: any) =>
    `해당 상품은 방갯수가 ${n}개 이하인 숙소에 적합합니다.`,
  product2_detail3:
    "잔다에서 무료로 제공하는 홈페이지를 제공받으실수 있습니다.a",
  product2_detail4: "사용기한은 한달이며 한달후 재결제가 이루어집니다.a",
  product3_detail1: "호텔 같은 큰규모에 적합한 상품.a",
  F_product3_detail2: (n: any) =>
    `해당 상품은 방갯수가 ${n}개 이하인 숙소에 적합합니다.`,
  F_product3_detail3:
    "잔다에서 무료로 제공하는 홈페이지를 제공받으실수 있습니다.a",
  F_product3_detail4:
    "홈페이지 커스텀 제작을 요청하실수 있으며, 별도 비용이 발생할수 있습니다.a",
  F_product3_detail5: "사용기한은 한달이며 한달후 재결제가 이루어집니다.a",
  room_gender: "방성별a",
  current_status: "현재상태a",
  do_modify: "수정하기a",
  product_memo: "상품 메모a",
  left_days: "남은일수a",
  room_setting: "방설정a",
  roomType_dose_not_exsist: (
    <span>
      방타입이 <Mbr /> 존재하지 않습니다. a
    </span>
  ),
  add_roomType: "방타입추가a",
  applies_to_all_reservations_booked_together: "함께 예약된 예약에 모두 적용a",
  update_roomType_completed: "방타입 업데이트 성공a",
  update_roomType_fail: "방타입 업데이트 실패a",
  remove_roomType_completed: "방타입 삭제성공a",
  remove_roomType_fail: "방타입 삭제실패a",
  create_roomType_completed: "방타입 생성성공a",
  create_roomType_fail: "방타입 생성실패a",
  opps_something_problem_happend: "이런! 문제가 발생했습니다.a",
  create_house: "숙소생성a",
  change_house: "숙소변경a",
  change_house_fail: "숙소 변경 실패a",
  please_create_house: " 숙소를 생성해주세요.a",
  update_complete: "업데이트 완료a",
  update_fail: "업데이트 실패a",
  create_season_complete: "시즌 생성완료a",
  create_season_fail: "시즌 생성실패a",
  delete_season_complete: "시즌 삭제완료a",
  delete_season_fail: "시즌 삭제실패a",
  delete_booking: "예약삭제a",
  change_complited: "변경완료a",
  change_failed: "변경실패a",
  create_season: "시즌생성a",
  season: "시즌a",
  do_create: "생성하기a",
  do_delete: "삭제하기a",
  priority: "우선순위a",
  basic_price_is_used_when_season_is_un_setted:
    '시즌이 적용되지 않는 기간 동안 "기본가격"을 사용합니다.',
  nth: "순위a",
  when_day_of_week_price_is_not_setted_basic_season_price_will_be_used:
    '"요일별 가격"이 적용되어 있지 않은 요일에는 시즌 기본가격을 따릅니다.',
  when_season_multiple_applyed_use_left_side_value_will_be_used:
    "시즌이 중첩된 있는 동안에는 좌측 시즌 가격을 사용합니다a",
  set_daily_price: "일별가격 설정a",
  day_of_week_price: "요일별가격a",
  room_name: "방이름a",
  season_name: "시즌명a",
  season_period: "시즌기간a",
  rep_color: "대표색상a",
  logOut: "로그아웃a",
  booker_name: "예약자명a",
  admin_screen: "관리자 화면a",
  logOut_complete: "로그아웃 완료a",
  the_memo_gives_an_alarm_on_the_next_connection:
    "해당 메모는 다음 접속시 알람을 줍니다.a",
  no_notes_are_currently_created: "현재 작성된 메모가 없습니다.a",
  not_a_valid_name: "올바른 이름이 아닙니다.a",
  not_a_valid_email: "올바른 이메일이 아닙니다.a",
  please_aree_to_info_offer: "정보제공 동의를 해주세요a",
  password_is_not_matched: "패스워드 확인이 일치하지 않습니다.a",
  not_a_valid_password: "올바른 비밀번호가 아닙니다.a",
  not_a_valid_phoneNumber: "올바른 휴대폰 번호가 아닙니다a",
  please_enter_a_base_price: "기본가격을 입력바랍니다.a",
  please_specify_the_date: "날자를 지정해주세요.a",
  please_select_a_payment_method: "결제방법을 선택해주세요.a",
  please_select_a_payment_status: "결제상태를 선택해주세요.a",
  please_select_reservation_status: "예약상태를 선택해주세요.a",
  please_enter_booker_name: "예약자명을 입력해주세요a",
  please_enter_phone_number: "전화번호를 입력해주세요.a",
  not_a_valid_mobile_number: "올바른 휴대폰 번호가 아닙니다.a",
  are_you_sure_you_want_to_delete_the_reservation:
    "정말 예약을 삭제하시겠습니까?a",
  booker: "예약자a",
  basic_price: "기본가격a",
  created_house: "생성한 숙소a",
  do_copy: "복제하기a",
  change_profile: "프로필 변경a",
  phoneNumber: "전화번호a",
  booking_status: "예약상태a",
  chnage_priority: "순위변경a",
  view_info: "정보보기a",
  use_color_setting_function: "색상 설정 기능a",
  display_related_setting: "배정관련 설정a",
  someone_is_making_a_reservation: "누군가 예약을 진행중 입니다.a",
  block_room: "방막기a",
  color_set: "색상설정a",
  block_room_completed: "방막기 완료a",
  update_profile: "프로필 업데이트a",
  update_profile_fail: "프로필 업데이트 실패a",
  apply_this_product_to_house: "이 상품을 숙소에 적용하기a",
  JANDA_provide_free_homepage_for_guest:
    "잔다 고객분들에게 무료 홈페이지를 제공합니다.a",
  check_our_samples: "샘플들을 살펴보세요.a",
  do_you_want_request_making_homepage: "홈페이지 제작을 신청하시겠습니까?a",
  block_room_failed: "방막기 실패a",
  will_only_use_the_reservation_system: "예약시스템만 사용하겠습니다.a",
  assig_completed: "배정완료a",
  assig_failed: "배정실패a",
  delete_completed: "삭제완료a",
  delete_failed: "삭제실패a",
  language_setting: "언어설정a",
  room_block_release: "방막기 해제a",
  room_block_release_fail: "방막기 해제 실패a",
  create_memo_completed: "메모 생성완료a",
  create_memo_fail: "메모 생성실패a",
  homepage_manual: "홈페이지 메뉴얼a",
  manual_download_complete: "메뉴얼 다운로드 완료a",
  manual: "메뉴얼a",
  provides_a_tab_that_can_be_divided_by_status_in_the_assignment_calendar:
    "배정달력에서 방태입별로 나누어볼수있는 탭을 제공a",
  file: "파일a",
  unPaid: "미결제a",
  good_status: "정상a",
  no_notifications: "알람이 없습니다.a",
  new: "newa",
  booker_info: "예약자정보a",
  caution: "주의a",
  mark_new_reservation: "새로운 예약을 표시합니다.a",
  room_type_tab: "방타입별 탭a",
  product_has_expired: "상품이 만료되었습니다.a",
  the_current_product_has_expired_normal_service_is_not_possible_Please_proceed_with_the_payment:
    "현재 상품이 만료되었습니다. 정상적인 서비스가 불가능합니다. 결제를 진행 해주세요.a",
  download: "다운로드a",
  start_experience: "체험시작a",
  house_adress: "숙소주소a",
  no_house_currently_created: "현재 생성된 숙소가 없습니다.a",
  F_selected_product_apply_to_house: (houseName: any) => (
    <span>
      * 선택하신 서비스는 숙소
      <span className="JDtextColor--point">{` ${houseName} `}a</span>에
      적용됩니다. a
    </span>
  ),
  currently_applied_service: "현재 적용된 서비스a",
  please_request_through_helpline: "상담전화를 통해 요청바람니다.a",
  can_use_after_phone_auth: "휴대폰 인증후 사용가능a",
  if_you_choose_wrong_size_product_to_house_service_can_be_stop:
    "규모에 맞지 않는 숙소를 선택하실 경우에 서비스가 중지 될수 있습니다.a",
  select_service: "서비스 선택a",
  release_service: "서비스 해제a",
  detail: "상세a",
  detail_adress: "상세주소a",
  please_search_house_location: "숙소위치를 검색해주세요.a",
  F_have_x_days_left_to_try_for_free: (daysLeftToExpire: string) =>
    `서비스 종료 까지 ${daysLeftToExpire} 남았습니다.`,
  F_user_name_hello: (userName: any) => `${userName}님 안녕하세요.`,
  F_user_name_good_luck: (userName: any) =>
    `${userName}님 좋은 일 가득하길 기원합니다.`,
  F_user_name_have_a_bright_day: (userName: any) =>
    `${userName}님 오늘도 힘찬 하루 되세요.`,
  F_have_house_count_n: (n: any) => `숙소 ${n}개 보유중`,
  F_you_have_x_free_trial_left_y__is_about_to_expire: (
    daysLeftToExpire: any,
    expireDate: any
  ) =>
    `무료 테스트 기간이 ${daysLeftToExpire} 남았습니다. ${expireDate} 만료예정.`,
  no: "아니요a",
  yes: "예a",
  guestHouse: "게스트하우스a",
  hotel: "호텔a",
  motel: "모텔a",
  pension: "펜션a",
  hostel: "호스텔a",
  sms_history: "SMS 내역a",
  please_verify_your_mobile_phone_to_ensure_smooth_service: (
    <span>
      원활한 서비스진행을 위해 <br /> 핸드폰 인증을 해주세요. a
    </span>
  ),
  delete_template_completed: "템플릿 삭제완료a",
  delete_template_failed: "템플릿 삭제실패a",
  update_template_completed: "템플릿 업데이트 완료a",
  update_template_failed: "템플릿 업데이트 실패a",
  create_house_completed: "숙소생성완료a",
  youth_hostel: "유스호스텔a",
  please_select_the_accommodation_type: "숙소타입을 선택 해주세요.a",
  the_max_count_of_houseName_is_20: "숙소명은 최대 20글자 입니다.a",
  please_enter_the_name_of_the_house: "숙소명을 입력해주세요.a",
  have_a_bright_day_sir: "오늘도 밝은 하루 보내세요a",
  the_price_is_too_low_are_you_sure_to_set_this_price: (
    <span>
      가격이 1000원 이하입니다. <br />
      정말설정하실려는 가격이 맞나요? a
    </span>
  )
};

export default en;
