import React from "react";
import Mbr from "../atoms/mbr/Mbr";

export const kr = {
  additionaly_setting_to_will_good_for_manage_ment: (
    <span>
      추가로 다음과 같은 설정을 해두시면 <Mbr /> 숙소운영에 도움이 될거에요!
    </span>
  ),
  default_setting_is_compelted: (
    <span>
      기본설정이
      <Mbr /> 완료 되었습니다.
    </span>
  ),
  make_it_easy_to_guide_accommodation_for_guests: (
    <span>
      게스트에게 숙소 이용 <Mbr />
      안내를 편리하게 해보세요.
    </span>
  ),
  try_setting_it_up_different_prices_by_date: (
    <span>
      날자별로 가격을 다르게
      <Mbr /> 설정해보세요.
    </span>
  ),
  Pricing: "가겨설정",
  choseCheckInDate: "체크인 날자를 선택해 주세요.",
  choseCheckOutDate: "체크아웃 날자를 선택해 주세요.",
  checkIn: "체크인",
  go_to_set: "설정하러 가기",
  automatically_send_prompts_to_your_guests: (
    <span>
      게스트에게 안내문자를
      <Mbr />
      자동 발송해 보세요.
    </span>
  ),
  sms_setting: "SMS설정",
  checkOut: "체크아웃",
  checkin_date: "체크인 날자",
  checkout_date: "체크아웃 날자",
  HM: "하우스메뉴얼",
  bookingList: "예약목록",
  cancleBooking: "예약취소",
  sendSMS: "문자전송",
  delete: "삭제",
  turn_off_alarm: "알림해제",
  timeout_please_request_again: "시간초과 다시 요청 해주세요.",
  there_is_an_alarm_set_note: "알람 설정된 메모가 있습니다.",
  group_notification: "단체알림",
  alarm: "알림",
  alarm_transmission_failed: "알람 전송 실패",
  alarm_transmission_completed: "알람 전송 성공",
  page_does_not_exist: "페이지가 존재하지 않습니다.",
  go_back_to_home: "홈으로 돌아가기",
  noti_setting: "알람 설정",
  note_updated: "메모 업데이트 완료",
  note_updated_failed: "메모 업데이트 실패",
  deleted_note_completed: "메모 삭제 완료",
  deleted_note_failed: "메모 삭제 실패",
  keep_noti: "계속 메모를 뛰우세요.",
  close_today: "하루동안 뛰우지 마세요.",
  authenticate: "인증하기",
  certification_number: "인증번호",
  mobile_phone_verification_number: "휴대폰 인증번호",
  certification_number_sent: "인증번호 발송완료",
  certification_number_sent_fail: "인증번호 발송실패",
  deleteBooking: "예약삭제",
  minute: "분",
  second: "초",
  block_place: "자리막기",
  nextResv: "다음 예약 ",
  make_reservation: "예약하기",
  send_notification: "알림 보내기",
  allocation_calendar: "배정달력",
  noti_target: "알림 대상",
  noti_level: "알람 중요도",
  checkDelete: "개를 삭제하시겠습니까?",
  check_net_status: "네트워크 연결상태를 확인해주세요!",
  checkCheckInDate: "체크인 날자를 선택해 주세요.",
  please_select_date: "날자를 선택해 주세요",
  reservation_creation_complete: "예약 생성 완료",
  reservation_creation_fail: "예약 생성 실패",
  reservation_update: "예약 업데이트",
  reservation_update_fail: "예약 업데이트 실패",
  reservation_delete_complete: "예약 삭제 완료",
  reservation_delete_fail: "예약 삭제 실패",
  year: "년",
  month: "월",
  calender_date: "달력날자",
  date: "일",
  till: "까지",
  mon: "월",
  tue: "월",
  wed: "월",
  thu: "목",
  fri: "금",
  sat: "토",
  sun: "일",
  next: "다음",
  prev: "이전",
  page: "페이지",
  row: "열",
  select: "선택",
  fullRoom: "만실",
  cancel: "취소",
  confirm: "확인",
  we_collect_your_personal_information_to_provide_the_service:
    "서비스 제공을 위해 귀하의 개인정보를 수집합니다.",
  is_selected_info_collect: "선택 정보가 맞나요?",
  selection_information_is_correct: "선택 정보가 맞습니다.",
  privacy_item: "개인정보 항목",
  consent_to_collection_of_personal_information: "개인정보 수집 동의",
  purpose_of_collection: "수집 목적",
  the_minimum_personal_information_required_to_provide_the_service_is_required_to_use_the_service:
    "서비스 제공을 위해 필요한 최소한의 개인정보이므로 동의를 해주셔야 서비스를 이용하실수 있습니다",
  smooth_reservation_management: "원활한 예약 관리",
  six_months_after_stay: "숙박후 6개월",
  if_you_violate_the_accommodation_policy_your_personal_information_will_be_saved_with_the_violation:
    "숙박 규정을 위반할 시 위반내용과 함께 개인정보가 저장됩니다.",
  try_to_create_in_SMS_settings: "SMS 설정에서 생성 해보세요.",
  write_a_description_of_the_menu: "해당 메뉴의 설명을 적어보세요.",
  retention_period: "보유 기간",
  msg_content: "문자내용",
  name: "이름",
  view_terms: "약관보기",
  contact: "연락처",
  Headcount: "안원수",
  find_destination: "대상찾기",
  outgoing_destination: "발신대상",
  guest: "게스트",
  login: "로그인",
  signUp: "회원가입",
  room_info: "객실정보",
  roomType: "방타입",
  bedIndex: "침대번호",
  gender: "성별",
  room: "방",
  auto_send_whether: "자동발신 여부",
  auto_send_target: "자동발신 대상",
  auto_send_condition: "자동발신 상황",
  sms_template: "문자템플릿",
  send_sms: "문자발신",
  male: "남",
  female: "여",
  make_payment: "결제하기",
  payment_info: "결제정보",
  password: "비밀번호",
  send_status: "발신상태",
  send_complete: "송신완료",
  graph_shape: "그래프 형태",
  send_fail: "송신실패",
  payment_status: "결제상태",
  total_price: "총가격",
  method_of_payment: "결제수단",
  people: "명",
  memo: "메모",
  HM_title: "하우스 메뉴얼 타이틀",
  current_set_number: "현재 설정된 번호",
  send_text_to_host: "호스트에게 문자 보내기",
  check_location_with_google_map: "구글맵으로 위치 확인하기",
  please_select_the_number_of_people: "인원수를 선택해주세요.",
  payment_canceled: "결제가 취소 되었습니다.",
  no_choosen_option: "선택사항이 없습니다.",
  information_does_not_exist: "정보가 존재하지 않습니다...",
  money_unit: "원",
  send: "전송",
  index: "번호",
  noti_title: "알림 제목",
  noti_period: "알람 기간",
  date_of_creation: "생성일시",
  houseName: "숙소명",
  house_reservation: "숙소 예약",
  transmission_time: "전송시간",
  are_you_sure_you_want_to_delete_this_guest: "해당 게스트를 삭제하시겠습니까?",
  others_booked_by_the_reservation_will_not_be_erased:
    "해당 예약자가 예약한 다른 인원들은 지워지지 않습니다.",
  dormitory: "도미토리",
  receiver: "수신자",
  invalid_password: "잘못된 패스워드입니다.",
  only_remove_that_guest: "해당 게스트만 제거",
  remove_all_reservations_booked_together: "함께 예약된 모든 예약 인원 제거",
  username_must_be_email: "아이디는 이메일 이여야합니다.",
  copy_reservation_page_URL: "예약페이지 URL 복사",
  login_complete: "로그인 완료",
  auth: "인증",
  house_create: (
    <span>
      숙소
      <Mbr />
      생성
    </span>
  ),
  product_registration: (
    <span>
      상품
      <Mbr />
      등록
    </span>
  ),
  passwords_do_not_match: "패스워드가 일치하지 않습니다.",
  cant_find_this_email: "해당 이메일을 찾을수 없습니다.",
  if_you_set_up_an_SMS_template_you_can_conveniently_send_the_template_when_you_send_a_message:
    "SMS 템플릿을 설정해두시면 메세지를 보낼떄 해당 템플릿을 편리하게 보낼수 있습니다.",
  view_SMS_history: "SMS 내역보기",
  create_template: "템플릿 생성",
  create_a_new_template: "새로운 템플릿을 생성하세요.",
  send_type: "발신타입",
  choose_product: "상품선택",
  useing: "사용중",
  basic_offer: "기본제공",
  light_type_layout: "light 타입 레이아웃",
  heavy_type_layout: "heavy 타입 레이아웃",
  please_inquire_separately: "별도 문의 바랍니다.",
  additional_cost: "추가비용",
  only_on_first_purchase: "첫구매시에만 발생",
  take_a_look: "살펴보기",
  apply: "신청하기",
  product_application_completed: "상품 신청 완료",
  product_application_failed: "상품 신청 실패",
  reservation_confirm: "예약확인",
  witch_statistics_do_you_want: "어떤 통계를 원하시나요?",
  input_your_name_please: "이름을 입력해주세요.",
  input_your_password_please: "비밀번호를 입력해주세요.",
  please_enter_your_phone_number: "전화번호를 입력해주세요.",
  date_of_statistics: "통계날자",
  change_statistics: "통계변경",
  which_unit_would_you_like_to_see: "어떤 단위로 보여 드릴까요?",
  status: "상태",
  Rooms: "객실",
  sales_statistics: "매출통계",
  statistical_transformation: "통계 변환",
  reservation_information: "예약정보",
  reservation_lookup: "예약조회",
  personnel: "인원",
  usage_amount: "이용금액",
  block_highlights: "블록 하일라이트",
  Apply: "적용",
  memo_content: "메모내용",
  unapplied: "적용해제",
  apply_color: "적용색상",
  completed: "완료",
  modify: "수정",
  applies_to_all_reservations_booked_together: "함께 예약된 예약에 모두 적용"
};
